apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "node-app"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        name: node-app
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docregsec