apiVersion: v1
kind: Service
metadata:
  name: "node-service"
  namespace: "develop"
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app: "node-app"